version: "3"
services:
    db:
        image: postgres
        container_name: chatdb
        ports:
            - "5432:5432"
    webapp:
        build: .
        container_name: chatapp
        ports:
            - "3000:3000"
        depends_on:
            - db
        image: webapp
    migration:
        image: webapp
        container_name: migration 
        command: npm run migrate:prod
        depends_on:
            - db
